# .streamlit/config.toml

[theme]
base="light"  # Use "light" for a light theme
primaryColor="#009c13"
backgroundColor="#c5d9f7"
secondaryBackgroundColor="#f7f7f7"
textColor="#252020"
font="sans serif"  # Use sans-serif font


